### PR TITLE
Pr/net bios name

### PR DESCRIPTION
**Pull request by hkusanic**

### CODE REVIEW

**Comment by Yvand** [comment]
@hkusanic: As discussed offline, please rename class Constant to Constants, and put it back in original namespace "ldapcp"
Can you also follow procedure https://help.github.com/articles/syncing-a-fork/ to sync your fork and fix the conflict (it must be with README.md file)?

**Comment by Yvand** [comment]
@hkusanic I reviewed the code and it looks great :)
But I made some changes in the code:
- Removed one LDAPCP.GetLDAPServerDirectories method
- Moved ResolveNetBiosDomainName method to RequestInformation so that it can be called by LDAPCP class as well
- Updated LDAPCP.GetLDAPServers to retrieve NetBIOS name is if's not set in the persisted object

But I think I found a bug in RequestInformation.ResolveDomainFromDirectoryPath(string directory):
When directory value looks like "YDCCollab.collab.YvanHost.local/dc=collab,dc=YvanHost,dc=local" method returns an empty dnsDomainName. This is bad because the domainname is not added correctly to claim values configured with a dynamic token.
As far as I can see it fails in RequestInformation.ResolveDnsDomainName, can you please take a look?

I pushed the changes in a new branch hkusanic-pr/netBiosName in my repo, normally that should sync with your own repo but I'm missing some knowledge here, maybe we can sync together to check this :)

**Comment by hkusanic** [comment]
Hi Yvand,


Thank you for your feedback.

I will take a look today [😊]

If I will have some time this week I will let you know and maybe we can schedule a call


Kind Regards,

Hrvoje


________________________________

**Comment by Yvand** [comment]
hi @hkusanic, do you have any news on this?

**Comment by hkusanic** [comment]
No sorry, was way too busy with other things.

Will let you know as soon as I have some time.
Hoppefuly this week [😊]


________________________________

**Pull request closed without merging**
